### ISSUE TITLE
Windows10-Python3.6.6 下运行报错

### ISSUE THREAD

**Issue by jwhsir** [Kaffaljidhmah2/pku_epidemic#5]
Python 3.6.6 Windows10

报错提示为：
C:\Users\Thinkpad\Downloads\Compressed\pku_epidemic-master>python main.py
Traceback (most recent call last):
  File "main.py", line 76, in <module>
    token = json.loads(r.text)['token']
  File "C:\Users\Thinkpad\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Thinkpad\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Thinkpad\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Kaffaljidhmah2** [comment]
可能得strip()一下哈
